Mouse : 907 : 260 : LeftButtonDown : 0 : 0 : 0
Mouse : 907 : 260 : LeftButtonUp : 0 : 0 : 0
DELAY : 500
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
