Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Mouse : 1250 : 155 : LeftButtonDown : 0 : 0 : 0
Mouse : 1250 : 155 : LeftButtonUp : 0 : 0 : 0
DELAY : 1000
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
DELAY : 1000
Mouse : 45 : 200 : LeftButtonDown : 0 : 0 : 0
Mouse : 45 : 200 : LeftButtonUp : 0 : 0 : 0
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
DELAY : 1000
Mouse : 1130 : 155 : LeftButtonDown : 0 : 0 : 0
Mouse : 1130 : 155 : LeftButtonUp : 0 : 0 : 0
DELAY : 1000
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
Keyboard : Enter : KeyDown
Keyboard : Enter : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F2 : KeyDown
Keyboard : F2 : KeyUp
Keyboard : F3 : KeyDown
Keyboard : F3 : KeyUp
Keyboard : Space : KeyDown
Keyboard : Space : KeyUp
DELAY : 1000
Mouse : 1888 : 288 : LeftButtonDown : 0 : 0 : 0
Mouse : 1888 : 288 : LeftButtonUp : 0 : 0 : 0
